[versions]
java = "17"
minecraft = "1.20.1"
fabric-loader = "0.15.11"
fabric-loom = "1.7-SNAPSHOT"
mixinsquared = "0.2.0-beta.5"

buildingwands = "2.6.9_release_fabric_1.20.1"
cctweaked = "MlxrTZqO"
forgeconfigapiport = "8.0.0"
fwaystones = "3.3.2+mc1.20.1"
gliders = "1.1.5+fabric"
itemcollectors = "1.1.10-fabric-mc1.20"
portinglib = "2.3.4+1.20.1"
supermartijn642core = "1.1.17-fabric-mc1.20.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

buildingwands = { module = "maven.modrinth:building-wands", version.ref = "buildingwands" }
cctweaked = { module = "maven.modrinth:cc-tweaked", version.ref = "cctweaked" }
forgeconfigapiport = { module = "fuzs.forgeconfigapiport:forgeconfigapiport-fabric", version.ref = "forgeconfigapiport" }
fwaystones = { module = "maven.modrinth:fwaystones", version.ref = "fwaystones" }
gliders = { module = "maven.modrinth:gliders", version.ref = "gliders" }
itemcollectors = { module = "maven.modrinth:item-collectors", version.ref = "itemcollectors" }
portinglib-config = { module = "io.github.fabricators_of_create.Porting-Lib:config", version.ref = "portinglib" }
portinglib-model-loader = { module = "io.github.fabricators_of_create.Porting-Lib:model_loader", version.ref = "portinglib" }
supermartijn642core = { module = "maven.modrinth:supermartijn642s-core-lib", version.ref = "supermartijn642core" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
